version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;uid=root;pwd=senha123;database=drhabit
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=senha123
      - MYSQL_DATABASE=drhabit
      - MYSQL_PASSWORD=senha123
    ports:
      - 3306:3306
    networks:
      - app-network

networks:
  app-network:
